Bump lombok, since it's not compatible with JDK21
There is error during compilation while running under JDK21:

java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid'

Following advice from https://github.com/projectlombok/lombok/issues/3393 seems to fix the issue

Signed-off-by: Richard Kosegi <richard.kosegi@gmail.com>